server: 
   port: 8881
http:
   proxyHost: 10.217.10.40
   proxyPort: 80

qhc: 
   bayern: 
      url: http://localhost:8880/bayern

# Database
spring: 
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.126.80.27:3306/qhc?charset=utf8mb4&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: frye
      password: 12345
      validation-query: select 1

# mybatis view sql
mybatis: 
   configuration: 
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#for email setting
mail:
#the directory for temp files
    files:
        path: "d:/qhc/mail/files"
########### test profile ###########
    debug: true
    host: 159.82.101.253
    username: 
    password: 
    smtp:
        from: ricoh-4000@carrier.utc.com
        auth: false
        timeout: 120000
        port: 25


# Bestsign config
contract: 
    bestsign:
       contractDir: D:\\qhc\\contracts\\        
       url: https://api.bestsign.cn
       accountname: peng.liu@carrier.utc.com
       entername: 青岛海尔开利冷冻设备有限公司
       clientid: 1555896956019659217
       secrete: CRUhcOhYjL2zpCOMvLzuIKrnS4WKP1W6
       sealname: 海尔开利公章
       privatekey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCVWoXXGgYKtIlpT4l4exar2zsaVxF1QgKqHpz/HmJ9LBRGj7S7q/SDtPDgB+3OYE2WwgdjgJnMcMiT1GmLeEagaseIryZseREJcRE+rdiLh1bkN6r1G4SWF2xRvg5FDKSIt5GOnJrEuICImv5QRJeqHg+Cx7vFngp41vorGRB5w9qYZmPL09pcCSNgfqPBte+22CTLNS1C3hA1nzQSxnxN6Bh5caqMTcNy7LLTlbJtXUQ4Z1elo7gkfL44vIBtmvZj4lNiVZLmBLnHIQwDAauE1lkmVW9GA0mLjROmEzJ/qN/zgqjDe2jMkdGwrS2JuFBRdIldlSB8ySjVjomHgMVjAgMBAAECggEAQ2dUKeyjt2cc8LsllosugybwuIV86od8/lvMjNKgrk8bY3DtpxkGw/4AC4tohpAt1BEDFqPuRTbNPvJJI9mHPlSScpxhYekNiE5P8xKwPOA6lcqNzAq8PqSZjRaSCBWZl94IwezpaEjAMWaJyZ37OJpSc7pCgwA9R6X1x0eLiPfo5gZYn7N61HsOCQkfv30Cvk6rZ/zhBkgzd3kCAGuEj0ZQTvt6j8s0MN6RCCSXpRCZXo0mwq2oVc6Um+kr5pcQHg9kL1NjbDjGG6qWP/mOIBhn9Vc+j0F766uouaWagmcfBgSRfMGUE/qfIOSlvbBGKLN1n6d5jchoPE6XF1QfiQKBgQDod4O/WAhLbf62ZG875p09QfoM49erOEWkuVWIvuX7ywHvsSQYrHY7+TuVX7uTpd9TUMeHGfrC1sBDYV0BxXg+9TS1rf1YVn2VfOiYzWdiHA8F8HaO19kZ6k4boLZUOQaAqdGzJ+j+qwKY0ke9s7eRRmtLf9pTEULyrvqBPuPTPwKBgQCkeRcSL0ut4b4QRHg7mHpn1fXAQPaWOW17lCNLvh3/pKxlnlW+k7hM/YhZXhh+ITzHlS1lg8EHWJl3G0j1MbaNh9W/tsEo97g3AffUabxWDJXrcX7oIRjSZJEYo/GVY5KHeTrnhckpR7t1debfW4d8XME55G/Pek7XytL6vRqY3QKBgQCh2sSyLtrnmdgkqd0Audp00kEFRIXewrlKrXeuVCvQmlHoz08wlrNjom4n3JW/gVfyrGWf3SjJC7ilsV6OYy0LuLJQZKnmHaImuOdBrJH0r1COdBQ39HVGI+rqNYV9Mo8iehp1QK5q0ipmuNIWdNC0p3EBCi26dGRGkCn+XwlFBQKBgQCAUmmJqpTlKUdc8c7M0H5QHUMLqKO7OTsOO9n98mr9VcGb1xkXA7G7f+Otthht8Ai3vtAYb99el+XEY+lcRFklu2Etnqy+BegYItT1STnD+TXO6FIXUhtHq2b5To/h+joMsK0gjeUQ7AJ59m8WvRbMFKI9RNlniwmQm5JYRspFkQKBgQCRGys8S3rcVmoB/C0CC00CW9I5xMJFGK5gRo0HspJ92H4Ch90w0Uya4YnPBw7liIOvW2MjWhIKLN9cL1nTQ7V2ZFnwMgYdWCDEq77WqVVT6+YNy3NvnWV/GPpll3Gkthe/VG75vmkli1oSaXLrLHOm45uYCXZhA+K16Y4aJwgP/w==
        

bpm:
    url: http://10.126.80.15/UltimusResources/SaleToolService.asmx?wsdl
  
sap:
    currency:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD024
        param: "[{\"key\": \"KURST\", \"value\":\"M\"},{\"key\": \"LANGU\", \"value\":\"1\"}]"
    customer:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD018
        param: "[{\"key\": \"DATUM\", \"value\":\"20190404\"}]"
    incoterm:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD034
        param: "[{\"key\": \"LANGU\", \"value\":\"1\"}]"
    clazz:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q091_MDM016
    characteristic:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q091_MDM017
    sapOfficeGroup:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD017
    paymentplan:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD023
    material:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q091_MDM014
    price:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD028
    priceA:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD028A  
    # 产品物料查询接口
    bomExplosion:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q090_MDM015 
    defaultCharacteristics:
         addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=ZQHC_MDM_Q037_FM004
    color:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=ZQHC_PPF_Q045_PP016
#实时查询订单状态
    queryOrderStatus:
       addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD029  
     
    # 下发订单
    sapCreateOrder:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD031
    # 修改订单
    sapChangeOrder:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD032