server: 
   port: 8881
http:
   proxyHost: 10.217.10.40
   proxyPort: 80

qhc: 
   bayern: 
      url: http://localhost:8880/bayern

# Database
spring: 
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.126.80.27:3306/qhc?charset=utf8mb4&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: frye
      password: 12345
      validation-query: select 1

# mybatis view sql
mybatis: 
   configuration: 
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#for email setting
mail:
#the directory for temp files
    files:
        path: "d:/qhc/mail/files"
########### test profile ###########
    debug: true
    host: 159.82.101.253
    username: 
    password: 
    smtp:
        from: ricoh-4000@carrier.utc.com
        auth: false
        timeout: 120000
        port: 25


# Bestsign config
contract: 
    bestsign:
       contractDir: D:\\qhc\\contracts\\        
       url: https://api.bestsign.cn
       accountname: peng.liu@carrier.utc.com
       entername: 青岛海尔开利冷冻设备有限公司
       clientid: 1555896956019659217
       secrete: CRUhcOhYjL2zpCOMvLzuIKrnS4WKP1W6
       sealname: 海尔开利公章
       privatekey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7uoZrvi4+YMWUIBWuIN3up7Eto6JB3RHyC6xBaWGLVoAA4Vu/S9hOqimUdDSvdWVTUjcXI5iE9xohfKCY/Op/gmPil4gdavSV+1Y9PXYVaycrG+1QO+EaoncsdhPw7BVfynpckBM82KV8AYfm+kJLPLKejO/LWgCjBXkPtxMA7B2J3Hq2B6d9/zSl3XEJkXK4tLgTmQRKJMhAIH/k9h6uEiAcEVMowte0Gb0+2jkHebTQCZK7gSlfX4ddT0Z/0QETKNOYDyKGioqZBF2OiMatdxjVIMJzQVoFzyEd5cgyYHr2yy9S33Qgo/FxXOHlNh52ugJR9lV9PtPut16zgxIBAgMBAAECggEBAJzEPsxqnKNqnJP91xz6RVqunr7GDxGBUyMVrFtTbSm2ql4R01QEOjY201ItWHHNTzgtR+QCzbL7xs6ADHy1d/3THSZz9C7cyjMVGAc79Age2y6cu6hs2KYtVefDExP1kkPUCiqSBf6hzE+p15uDESlTHrZYa0cdebqpL1d4Ql5ZYIwYfCe6C4JusHVwFHFVIRfbj8qZw9lZ58sMVlXsisNGz4wb/DW3b6qDRCTyFhTg6DE+HW1SfpgEgSX0f9MsxtOTtP6n4JyWs+UbXlF3jRmMLkeCe/kdu0aMSD4//wA9sKzHnoXCPZwedM+NxShcmpfjw7TB7RrrOyQg2OKa4AECgYEA3KXm6fn3CYnG+l1NrrPQKAQLuvCrRAnek0gpGocnph4CfxcjRTDDLaqk29FyGNMeQdemoC8RHfGHWNZUnX2/1Fvzf/aOPzIUy6gGFIWwHnhBL63sp42pkTcLp0UV3y02LbSR5XRslhtr1PAfPpMJLu4iz80FDRsf36aK00+tQKECgYEA2c5mUKF3eS9o+WmtUDFpVxGhbmtxtMkY9YQgs+dHhqvlLgwGALauZairyLptpmcRZ+Iqhaxu8OxG6AOHVnU6jaxE91as3JK7f0ULl19WUy5k1omUtf3oq0Mb3vw2MiP6gqXDbtqEELvt01Fd34py+YqeekqJ6oH3CN3g5G/UdWECgYBPja1U3OAZ20gXir5wZ7p8QwErtIw7aseKGLFhNCuydA14XxJDZxJoC6eG7dwSYUP+f08/X9jvD985w4Uch3M7kK+Zin69AESJLRqMGatnQPpXw4CY5LWnes5Dz9/T6IwpLHqR3UktUdOuIalSOVdNSWTZwVS55fa2/2f8SjTwIQKBgQCHjG4cbACAiMLZxay4paebKju/Dlr7WdOQqCP6EktvQnckixMJSqeKWMhf6bXnw2kPr68q9b8tbL5MEjYd1mMUXEuname19hN+ByhJkmmU5uCWq5TDFjvAqckkou3PkpiKykKwMInUKEDALHkxb2ZSarRqAw2FxlBJUlxtjjM4wQKBgHHTy2dTYP16QhXwAnVQNVKGNdYBHcdk1n0suVy3djwkQQtGa2dgWaRSZJbV62scW1t2kEz8I5zrcqvklFdWbfkcoARK3YgjqEkdHUuIk3W9BgXyvGbaR/vRE26jeE4OvyOCxIxXyif4h0R9CRU+kc05fZa1P4PF8ikXgNjH8Xw2
        

bpm:
    url: http://10.126.80.15/UltimusResources/SaleToolService.asmx?wsdl
  
sap:
    currency:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD024
        param: "[{\"key\": \"KURST\", \"value\":\"M\"},{\"key\": \"LANGU\", \"value\":\"1\"}]"
    customer:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD018
        param: "[{\"key\": \"DATUM\", \"value\":\"20190404\"}]"
    incoterm:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD034
        param: "[{\"key\": \"LANGU\", \"value\":\"1\"}]"
    clazz:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q091_MDM016
    characteristic:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q091_MDM017
    sapOfficeGroup:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD017
    paymentplan:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD023
    material:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q091_MDM014
    price:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD028
    priceA:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD028A  
    # 产品物料查询接口
    bomExplosion:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q090_MDM015 
    defaultCharacteristics:
         addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=ZQHC_MDM_Q037_FM004
    color:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=ZQHC_PPF_Q045_PP016
#实时查询订单状态
    queryOrderStatus:
       addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD029  
     
    # 下发订单
    sapCreateOrder:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD031
    # 修改订单
    sapChangeOrder:
        addr: http://sapp11.eu.carrier.utc.com:8001/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD032
     #查询订单状态
    queryStatus:
         addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD043
    