server: 
   port: 8881
http:
   proxyHost: 10.217.10.40
   proxyPort: 80

qhc: 
   bayern: 
      url: http://localhost:8880/bayern

# Database
spring: 
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.126.80.27:3306/qhc2?charset=utf8mb4&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: frye
      password: 12345
      validation-query: select 1

# mybatis view sql
mybatis: 
   configuration: 
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#for email setting
mail:
#the directory for temp files
    files:
        path: "d:/qhc/mail/files"
########### test profile ###########
    debug: true
    host: mailhub.carcgl.com
    username: 
    password: 
    smtp:
        from: qhcit@carrier.com
        auth: false
        timeout: 120000
        port: 

# Bestsign config
contract: 
    bestsign:
        contractDir: D:\\qhc\\contracts\\
        url: https://api.bestsign.info
        accountname: chunzhao.wang@carrier.com
        entername: 青岛海尔开利冷冻设备有限公司
        clientid: 1551431358012904950
        secrete: FB9KFCnfk1w9n1lRATGWHdCmiOf3Yt6J
        sealname: 青岛海尔开利冷冻设备
        privatekey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCT8nJ2xwoZbU20g5bA2V9xDVmFbK6cEctLgqyTaiVhC3t+muEu4KodoiiCMhiJgeQYzNHjxv4FKFxD9F5iSxVBREqSHd9KUamM3+yhHcDA8zalb9O9D9MZp6oP/9MerMrjnZC7KswtHME5nhElBQQdLgG5dDlK3TI/U17iUPY5mhfzBAoGyEiXdVwVzxZemzL8uWMl0+FVOgkf35R0oIz0SoV1748Dmuse0kqUdJltI8rByrOaS0UNwEtVhS8jC4fm6Aoly3/pwViHhCUouU73flzbHVCi74pZ8pJCH7UecM2P7C0aIWY+9FBRVBf0W5peEfZHFY0dYbPUUne52OuVAgMBAAECggEAVtjAdpcah5iRP8DrEuPHUe7bOSZ2TWlopDfeJF7v+EqsQMKcI0+ArQqOqvbLTpTwF9rL7uDWJqLtnnppmVun63syJxngBJlxZR/hoSZ9Cwb6chz194q9idbRTrkG7n/STdElr6lM18KEbtUqDUgnhRWHr5zZMOgt4dyH22RZVbAHcXSF6byDtc4RRpvEDGAjpxJZRUbgHq7G/kgXqoZYh3qfT/YlWULUyK1GPZWGu958fgswbRezFBGPo146IwfEbPykoIJg2AiQqmTBVp881SEVuqVWcM12UAt4wnY4jNzsvAwZFFHe1nOzwRAUfF3KZocZR+jM+XPB86IylmA4IQKBgQDfPKByf2rVX0TWDmcLflRrtm7MXHtaVr21A0uxIjNgVlNevnKNFXQ2C2wZ2Gts4dWJSTNpVwLINre2jxbNKQRB14GWRoPyTl3EkDieTaTOWxd/rFr6cZhDml7v4s7wTBik/2S+Z+SJbpFM/BNlv2X5eqwkrfIUHQ/xcI/H9Uz+aQKBgQCpqQ+BQvSRVA87MjT+FCwv+RFFz+LV6vL6XtkRLE9osZ1g7Nwi4UYYfROkv2QkyFTVojI4cn0F0J8BRmU+MBNmy2s01067GaIBK8gmxw9XnGi1TFZbE3vC73MaNhCzVw/+m+cHNG5BwHxkMgurpjwgWATOWc72iLxQHk0fW4x2TQKBgQC9yYhK74K/NoiKR6JZhiR1kpruCS4h5p7QFqYySPZOz/V/FgDDa1rqW5mi+3iREAp/9gjMZNoLp2FWxp3G/DkPVQ1p2jdxOCjF5SsNgss7WPxIYhrS0uJ1jvdpkHUInFlTZYGb0y3bnXHQdnpzRV6H1EAnyu6FJRQZ2u2SPT0hCQKBgDIPyp1vrk67qQrkk7JtLWSyb6BT6TEJ9Mxf9FkW5A+WaUPSYFqCcnaDYap5NwmLe0zWYU86qR1wI5rytKkW8oKgf2/GIFshAyapTpPypNpLMrJcZhbVtu0cTrBrR55DkFqmkhMUK3yHWa0O/1aU5KT+k9x3r5QbYMWbS1J3Zwj5AoGBAMNsxUEMP/IrNRgfKIfy81YyViG/hSKiYiQoBbhGPt0XgoM8SgTH/N6g5YC1+++ZjiijLrMY9AwoQeESdLQtTrGz9KvibpcSnNGG6/y/fyhl8Ug5TGTCH3KlhogKkRBJ6I+NjxKbkiTupmr5yc4DsPPRFhtbH+iWqid89HujDtkI
      

bpm:
    url: http://10.126.80.27:88/UltimusResources/SaleToolService.asmx?wsdl
  
sap:
    currency:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD024
        param: "[{\"key\": \"KURST\", \"value\":\"M\"},{\"key\": \"LANGU\", \"value\":\"1\"}]"
    customer:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD018
        param: "[{\"key\": \"DATUM\", \"value\":\"20190404\"}]"
    incoterm:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD034
        param: "[{\"key\": \"LANGU\", \"value\":\"1\"}]"
    clazz:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q091_MDM016
    characteristic:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q091_MDM017
    sapOfficeGroup:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD017
    paymentplan:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD023
    material:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q091_MDM014
    price:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD028
    priceA:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD028A
    # 产品物料查询接口
    bomExplosion:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q090_MDM015
    defaultCharacteristics:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=ZQHC_MDM_Q037_FM004
    color:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=ZQHC_PPF_Q045_PP016 
#实时查询订单状态
    queryOrderStatus:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD029
     
    # 下发订单
    sapCreateOrder:
#        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD031
         addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD041
    # 修改订单
    sapChangeOrder:
#        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD032
         addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD042
   #查询订单状态
    queryStatus:
         addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD043
