server: 
   port: 8881

qhc: 
   bayern: 
      url: http://localhost:8880/bayern

# Database
spring: 
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.126.80.27:3306/qhc2?charset=utf8mb4&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: frye
      password: 12345
      validation-query: select 1

# mybatis view sql
mybatis: 
   configuration: 
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Bestsign config
contract: 
    bestsign:
        contractDir: D:\\qhc\\contracts\\
        url: https://api.bestsign.info
        accountname: yongzheng.wang@haiercarrier.com
        entername: \u9752\u5C9B\u6D77\u5C14\u5F00\u5229\u51B7\u51BB\u8BBE\u5907\u6709\u9650\u516C\u53F8
        clientid: 1575947454016605528
        secrete: jmx9U6HyaV1O54lxk1aLYgwhn4SCocwy
        sealname: \u9752\u5C9B\u6D77\u5C14\u5F00\u5229\u51B7\u51BB\u8BBE\u5907
        privatekey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJFstcFiHwxvod0kQU1KLi+Sy7bE3yrfVPeTd3jdPw3qmCik21wLUfXXO6/dSQyTWV3sSoJGNoK6jlhqKbbDottDOVE1T5G6Wc2Nz3YyfGq76EO9C+do7y4WPxqq+1tOoLi5DO7pjMdN7kXS0fyDFJhbUGWroPsNV1IbsGTB1ipzAgMBAAECgYA9z8cxe1NXJdvW8yIOiAk5j1unQ+bXgjXLRZLyfJfggmZKYEgcx3L+240zIwt5nOfPVDAXT2C8EC+QxQ8V7/G4OxpZ7XeVEP0MaI0qRZn7/J5BEsEpd1UNOJVWL7Sd0fl4EzL5nLerKLxjv1sNnXZhExtykbM81DwwaBx+/vRfgQJBAN51ykGBQ0IJHIqz1mpL7G4yUtNQ5iuzj7ZRrndz7sdfVnOiqf2K/YvxgC7OV1lZggNAIEcO42vPID4PxkvqP8UCQQCnWZxZQD2g4RxNIQnrvAWFfhYa+A/dha+ZsP/unTV5XdFRhJ55J8yx4/RKxVPFQ7PiwY0s73o6OcdeK6fEHezXAkBgKDoMpnsUCCw2KBX+TGMeHtJ+VPGo4iy0egoXyBzmQOd1hFJGLdX6r6DgmoBXNsFj9kv9awoSh61AJkFofxChAkBJTH2ntfSIX7EGs17mCr+cXcKO43IHhAOK3LTsrZz7YLVK8Dx9Mop8rCyXB2EOuP20ZzRPp0Cw+hexzos34ieXAkEAsZIOtp0UZU9KIK7SSwHuH2fqHGI/axqYCjYt1CO0l1DIySsCilPjiD6gkziz3ClJrYvR8KZU7+ZZe0udNg7/3g==

bpm:
    url: http://172.17.5.50/UltimusResources/SaleToolService.asmx?wsdl
  
sap:
    currency:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD024
        param: "[{\"key\": \"KURST\", \"value\":\"M\"},{\"key\": \"LANGU\", \"value\":\"1\"}]"
    customer:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD018
        param: "[{\"key\": \"DATUM\", \"value\":\"20190404\"}]"
    incoterm:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD034
        param: "[{\"key\": \"LANGU\", \"value\":\"1\"}]"
    clazz:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q091_MDM016
    characteristic:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q091_MDM017
    sapOfficeGroup:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD017
    paymentplan:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD023
    material:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q091_MDM014
    price:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD028
    priceA:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD028A  
    # 产品物料查询接口
    bomExplosion:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_MDM_Q090_MDM015 
    defaultCharacteristics:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=ZQHC_MDM_Q037_FM004  
    # 下发订单
    sapCreateOrder:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD031
    # 修改订单
    sapChangeOrder:
        addr: http://sapt11.eu.carrier.utc.com:8002/sap/xi/zqhc_service?sap-client=220&method=Z_QHC_SD_Q091_SD032
