package com.qhc.order.entity;import java.io.Serializable;/** *  * Function: Data transfer object. <br>  * * @author walker */public class Order		implements Serializable {	private static final long serialVersionUID = 7510504186045858145L;		/* Id */	private Integer id = null;	/* 订单类型
            ZH0D	经销商订单
            ZH0M	备货订单
            ZH0T	大客户订单 */	private String orderType = null;	/* 序列号 */	private String sequenceNumber = null;	/* 签约单位/ 客户 */	private String customerCode = null;	/* 性质分类，经销商/直签 */	private String customerClazz = null;	/* 客户经理，如果是创建人就不需要 */	private String salesCode = null;	/* 销售工具订单类型
            1 经销商标准折扣下单
            2 经销商非标准折扣下单
            3 直签客户投标报价
            4 直签客户下定单
            5 备货  */	private String stOrderType = null;	/* 报价单状态
            00 报价单
            01 已中标
            02 已下单 */	private String quoteStatus = null;	/* 关联的报价单ID，报价单下单后的订单需要关联原有报价单 */	private Integer quoteOrderId = null;	public Order(){	}	public Integer getId() {		return this.id;	}	public void setId(Integer id) {		this.id = id;	}	 	public String getOrderType() {		return this.orderType;	}	public void setOrderType(String orderType) {		this.orderType = orderType;	}	 	public String getSequenceNumber() {		return this.sequenceNumber;	}	public void setSequenceNumber(String sequenceNumber) {		this.sequenceNumber = sequenceNumber;	}	 	public String getCustomerCode() {		return this.customerCode;	}	public void setCustomerCode(String customerCode) {		this.customerCode = customerCode;	}	 	public String getCustomerClazz() {		return this.customerClazz;	}	public void setCustomerClazz(String customerClazz) {		this.customerClazz = customerClazz;	}	 	public String getSalesCode() {		return this.salesCode;	}	public void setSalesCode(String salesCode) {		this.salesCode = salesCode;	}	 	public String getStOrderType() {		return this.stOrderType;	}	public void setStOrderType(String stOrderType) {		this.stOrderType = stOrderType;	}	 	public String getQuoteStatus() {		return this.quoteStatus;	}	public void setQuoteStatus(String quoteStatus) {		this.quoteStatus = quoteStatus;	}	 	public Integer getQuoteOrderId() {		return this.quoteOrderId;	}	public void setQuoteOrderId(Integer quoteOrderId) {		this.quoteOrderId = quoteOrderId;	}	 	@Override	public int hashCode() {		final int prime = 31;		int result = 1;		result = prime * result + ((id == null) ? 0 : id.hashCode());		return result;	}	@Override	public boolean equals(Object obj) {		if (this == obj) {			return true;		}		if (obj == null) {			return false;		}		if (getClass() != obj.getClass()) {			return false;		}		final Order other = (Order) obj;		return (this.id == null ? other.id == null : this.id.equals(other.id));	}		public String toString() {	    final String tab = "  ";	    String str = "";	    str = "Order ( "	        + "id = " + this.id + tab	        + "orderType = " + this.orderType + tab	        + "sequenceNumber = " + this.sequenceNumber + tab	        + "customerCode = " + this.customerCode + tab	        + "customerClazz = " + this.customerClazz + tab	        + "salesCode = " + this.salesCode + tab	        + "stOrderType = " + this.stOrderType + tab	        + "quoteStatus = " + this.quoteStatus + tab	        + "quoteOrderId = " + this.quoteOrderId + tab	        + " )";		    return str;	}}